### PR TITLE
Fix lots of xAOD::TAuxStore warning in OverlapRemover

### LINKED ISSUE #947: Troubles writing the output using a subclassed TreeAlgo
I finished updating job configuration so that latest xAH runs with 2.4.32. Now it passes successfully but the output seems to be empty and I get a lot of errors like below.

If I open the output file in `data-tree` I see all expected branches but they seem to be empty (nothing happens when double clicking on them).

Was there any non-backwards compatible change in xAH that could have caused it?

```
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1675 Couldn't determine if branch describes a single object or a container
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1677 ROOT type  : xAOD::AuxContainerBase
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1680 Object type: char
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1683 Vector type: std::vector<char>
xAOD::TAuxStore::setup... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:857 Branch type and requested structure mode differ for branch: ElectronsAux.
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1675 Couldn't determine if branch describes a single object or a container
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1677 ROOT type  : xAOD::JetAuxContainer_v1
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1680 Object type: char
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1683 Vector type: std::vector<char>
xAOD::TAuxStore::setup... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:857 Branch type and requested structure mode differ for branch: AntiKt4EMTopoJetsAux.
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1675 Couldn't determine if branch describes a single object or a container
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1677 ROOT type  : xAOD::JetAuxContainer_v1
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1680 Object type: char
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1683 Vector type: std::vector<char>
xAOD::TAuxStore::setup... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:857 Branch type and requested structure mode differ for branch: AntiKt4EMTopoJetsAux.
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1675 Couldn't determine if branch describes a single object or a container
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1677 ROOT type  : xAOD::JetAuxContainer_v1
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1680 Object type: char
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1683 Vector type: std::vector<char>
xAOD::TAuxStore::setup... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:857 Branch type and requested structure mode differ for branch: AntiKt4EMTopoJetsAux.
SeeSawTreeAlgo::execute() INFO    Making tree physics/nominal
HelpTreeBase()            INFO    HelpTreeBase setup
SeeSawTree                INFO    Creating output TTree
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1675 Couldn't determine if branch describes a single object or a container
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1677 ROOT type  : xAOD::AuxContainerBase
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1680 Object type: char
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1683 Vector type: std::vector<char>
xAOD::TAuxStore::setup... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:857 Branch type and requested structure mode differ for branch: ElectronsAux.
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1675 Couldn't determine if branch describes a single object or a container
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1677 ROOT type  : xAOD::AuxContainerBase
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1680 Object type: char
xAOD::TAuxStore::isCon... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:1683 Vector type: std::vector<char>
xAOD::TAuxStore::setup... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/xAODRootAccess/Root/TAuxStore.cxx:857 Branch type and requested structure mode differ for branch: ElectronsAux.
...
```

### PR DESCRIPTION
**Pull request by ntadej**
B-tag working point might not be set for overlap remover so we are trying to access an empty decorator. Avoid this.

Closes #947.

### CODE REVIEW

File: Root/OverlapRemover.cxx [hunk 1]
```diff
@@ -407,9 +407,11 @@ EL::StatusCode OverlapRemover :: fillObjectCutflow (const xAOD::IParticleContain
         break;
     }
 
-    SG::AuxElement::Decorator< char > isBTag( m_bTagWP );
     int isBTagged = 0;
-    if( isBTag.isAvailable( *obj_itr ) && isBTag(*obj_itr)==true ) isBTagged = 1;
+    if ( m_bTagWP.size() ) {
```
Comment (kratsg) [inline Root/OverlapRemover.cxx]: please use `std::string::empty()` like `m_btagWP.empty()` instead.

Comment (ntadej) [inline Root/OverlapRemover.cxx]: Fixed.
